### ISSUE TITLE
ember server fails to start with the error

### ISSUE THREAD

**Issue by millisami** [ember-mobile/ember-cli-framework7#3]
Using ember-cli
```
± ember -v                                                                                                           2.1.0
version: 0.1.9
Could not find watchman, falling back to NodeWatcher for file system events
node: 0.10.28
npm: 2.1.8
```
Generated the new app, then installed:
```
npm install --save-dev ember-cli-framework7
ember g ember-cli-framework7
```
Then starting the server fails:

```
± ember s                                                                                                            2.1.0
version: 0.1.9
Could not find watchman, falling back to NodeWatcher for file system events
Livereload server on port 35729
Serving on http://0.0.0.0:4200/
File: bower_components/framework7/src/js/dom7-intro
Unexpected token (65:6)
SyntaxError: Unexpected token (65:6)
    at raise (/Users/millisami/Emberapps/framework7/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:333:15)
    at unexpected (/Users/millisami/Emberapps/framework7/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1366:5)
    at parseExprAtom (/Users/millisami/Emberapps/framework7/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2153:7)
    at parseExprSubscripts (/Users/millisami/Emberapps/framework7/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2012:28)
    at parseMaybeUnary (/Users/millisami/Emberapps/framework7/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1995:16)
    at parseExprOps (/Users/millisami/Emberapps/framework7/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1946:24)
    at parseMaybeConditional (/Users/millisami/Emberapps/framework7/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1930:16)
    at parseMaybeAssign (/Users/millisami/Emberapps/framework7/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1913:16)
    at parseExpression (/Users/millisami/Emberapps/framework7/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1898:16)
    at parseStatement (/Users/millisami/Emberapps/framework7/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1586:38)
    at parseBlock (/Users/millisami/Emberapps/framework7/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:1826:18)
    at parseFunctionBody (/Users/millisami/Emberapps/framework7/node_modules/ember-cli/node_modules/broccoli-es6modules/node_modules/esperanto/node_modules/acorn/acorn.js:2378:19)
```

**Comment by takumikub** [comment]
Help me

**Comment by ericop** [comment]
I had this problem and solved it just today. Turned out on the top of one of my fileI had somehow got `==` in the ember import. Hope that gives later readers a place to look for syntax errors.
```
import Em==ber from ‘ember’
```

**Comment by spieker** [comment]
I'm unable to reproduce this issue, which version of Framework7 did you use? The addon always adds the latest version of F7 and since the reported file (`bower_components/framework7/src/js/dom7-intro`) is in the f7 bower package, it seems to be an issue of your F7 version.
